Make cassette player tracks wrap around
CaosCreations/SpaceTruckin pull request #131
Opened 2021-02-07 14:57 UTC by maxwellpark

2021-02-08 23:53 UTC, ambid17 requested changes

2021-02-08 23:53 UTC, ambid17 commented on Assets/Scripts/UI/CassettePlayer.cs
> +			? currentTrackIndex < tracks.Length - 1 ? currentTrackIndex + 1 : 0
NO. BAD. NO.

2021-02-10 00:40 UTC, maxwellpark commented on Assets/Scripts/UI/CassettePlayer.cs
> +			? currentTrackIndex < tracks.Length - 1 ? currentTrackIndex + 1 : 0
:(

2021-02-11 10:04 UTC, ambid17 approved these changes

2021-02-11 18:56 UTC, merged