Added the main menu button in the pause button
CaosCreations/SpaceTruckin pull request #605
Opened 2022-01-20 14:10 UTC by willy1989

2022-01-20 23:51 UTC, maxwellpark requested changes
Works well

2022-01-20 23:51 UTC, maxwellpark commented on Assets/Scripts/UI/PauseMenu/PauseMenuUI.cs
> +    [SerializeField] private Button MainMenuButton;
camelCase this please

2022-01-20 23:51 UTC, maxwellpark commented on Assets/Scripts/UI/PauseMenu/PauseMenuUI.cs
> +        MainMenuButton.onClick.RemoveAllListeners();
Can you use this extension method instead for adding the listener please, 
`mainMenuButton.AddOnClick()`;

It will do all that stuff and also add the UI sound effect. I set this up to be used for all the buttons.
![image](https://user-images.githubusercontent.com/61809127/150430960-4f2e0e9b-e628-4e0e-b057-847eb6fa5587.png)

2022-01-20 23:51 UTC, maxwellpark commented on Assets/Scripts/UI/PauseMenu/PauseMenuUI.cs
> +    private void Awake()
Could null check the button but not a big deal

2022-01-20 23:51 UTC, maxwellpark commented on Assets/Scripts/UI/PauseMenu/PauseMenuUI.cs
> +        UIManager.ShowCanvas(canvasType: UICanvasType.MainMenu, viaShortcut: false);
Looks good. 
Don't worry about this btw:
![image](https://user-images.githubusercontent.com/61809127/150439773-9b1f6b5b-00b9-47f4-8778-518326bcd025.png)
It's a slight issue with the canvas/player prefs that haven't got round to addressing. I don't think it actually makes any difference in practice in this case anyway.

2022-01-21 09:02 UTC, willy1989 commented on Assets/Scripts/UI/PauseMenu/PauseMenuUI.cs
> +    [SerializeField] private Button MainMenuButton;
Done

2022-01-21 09:12 UTC, willy1989 commented on Assets/Scripts/UI/PauseMenu/PauseMenuUI.cs
> +        MainMenuButton.onClick.RemoveAllListeners();
Done

2022-01-21 12:47 UTC, maxwellpark approved these changes

2022-01-25 09:34 UTC, merged