Add daily completed mission report and solution for storing missions completed in the past.
CaosCreations/SpaceTruckin pull request #92
Opened 2021-01-31 10:48 UTC by maxwellpark

The past mission data can later be used in the Analytics system.

2021-01-31 10:49 UTC, maxwellpark commented
This is somewhat of a WIP. But I have tested it and the core functionality works.
I need your opinion on the mission archiving. 
I moved some files around to make them more logically placed.

2021-02-08 23:38 UTC, ambid17 requested changes
for the love of god. fix line endings

2021-02-08 23:38 UTC, ambid17 commented on Assets/Scripts/DataModels/Missions/MissionOutcomes/PilotXpOutcome.cs
> +        PilotsManager.Instance.AwardXp(mission.Ship, xpGained);
pilots manager shouldn't need the ship

2021-02-08 23:38 UTC, ambid17 commented on Assets/Scripts/DataModels/Ships/Ship.cs
> +        if (CurrentMission != null)
add "else" condition with debug

2021-02-08 23:38 UTC, ambid17 commented on Assets/Scripts/Singletons/DataModelSingletons/ArchivedMissionsManager.cs
> +    public List<ArchivedMission> MissionsCompletedYesterday { get; set; }
clearing this should happen in this file

2021-02-08 23:38 UTC, ambid17 commented on Assets/Scripts/Singletons/DataModelSingletons/DataModelManagerInitialiser.cs
> +        MissionsManager.Instance.Init();
need to decouple these as this is gonna need to be async in the future

2021-02-08 23:38 UTC, ambid17 commented on Assets/Scripts/Singletons/DataModelSingletons/PlayerManager.cs
> +        if (playerData == null)
this check should probably be added everywhere after data loading

2021-02-08 23:38 UTC, ambid17 commented on Assets/Scripts/UI/Terminal/NewDayReportUI/NewDayReportUI.cs
> +        reportCardInstance = Instantiate(reportCardPrefab, transform);
dont instantiate every time. just turn it on/off and change the text

2021-02-12 20:12 UTC, ambid17 approved these changes

2021-02-13 23:02 UTC, merged